networks:
  laravel:

volumes:
  postgres_db:

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - laravel
    depends_on:
      - php
      - redis
      - postgres

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - UID=${APP_USER_UID}
        - GID=${APP_USER_GID}
    restart: unless-stopped
    volumes:
      - './:/var/www/html'
    networks:
      - laravel

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - laravel

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - 'postgres_db:/var/lib/postgres/data'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:${DB_PORT}"
    networks:
      - laravel
